### PR TITLE
Parse manifest to determine package name.

### LINKED ISSUE #1177: Error:Execution failed for task ':app:generateDebugR2'. > java.io.FileNotFoundException:
My **applicationId** is different with my **packageName**, it went wrong when gradle build: 

Error:Execution failed for task ':app:generateDebugR2'.
java.io.FileNotFoundException: ...\app\build\generated\source\r\debug\com\xxx\ **MyApplicationId(which should be MyPackageName)** \R.java (系统找不到指定的路径。)

But I have changed the application ID from the default one, which is same with the package name, for several weeks, the butter knife works well till yesterday. 

Gradle stack trace: 

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:generateDebugR2'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
**Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: ...\app\build\generated\source\r\debug\com\xxx\MyApplicationId\R.java (系统找不到指定的路径。)**
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:152)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 27 more
**Caused by: java.io.FileNotFoundException: ...\app\build\generated\source\r\debug\com\xxx\MyApplicationId\R.java (系统找不到指定的路径。)**
	at com.github.javaparser.Providers.provider(Providers.java:62)
	at com.github.javaparser.Providers.provider(Providers.java:66)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:212)
	at butterknife.plugin.FinalRClassBuilder.brewJava(FinalRClassBuilder.java:40)
	at butterknife.plugin.ButterKnifePlugin$configureR2Generation$1$1$$special$$inlined$apply$lambda$1.execute(ButterKnifePlugin.kt:67)
	at butterknife.plugin.ButterKnifePlugin$configureR2Generation$1$1$$special$$inlined$apply$lambda$1.execute(ButterKnifePlugin.kt:18)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	... 33 more

### PR DESCRIPTION
**Pull request by runningcode**
We don't want to use the applicationId to find the location of the
R.java file because the R.java file's location is based on the package
name not the applicationId.

The applicationId can change based on the variant, but the R.java file's
location will not change.

Added some tests to make sure this works based on the FixturesTest in
SQLDelight.

Fixes #1177

### CODE REVIEW

File: gradle/wrapper/gradle-wrapper.properties [hunk 1]
```diff
@@ -2,4 +2,4 @@ distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-4.4.1-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-4.5-all.zip
```
Comment (tasomaniac) [inline gradle/wrapper/gradle-wrapper.properties]: Do not update this manually. Always call the task wrapper with appropriate arguments to update. That will also update the wrapper jar and executables.

Comment (JakeWharton) [reply gradle/wrapper/gradle-wrapper.properties]: The jar and executables didn't change from 4.4 to 4.5.

File: butterknife-gradle-plugin/src/main/java/butterknife/plugin/ButterKnifePlugin.kt [hunk 2]
```diff
@@ -7,6 +7,7 @@ import com.android.build.gradle.FeaturePlugin
 import com.android.build.gradle.LibraryExtension
 import com.android.build.gradle.LibraryPlugin
 import com.android.build.gradle.api.BaseVariant
+import groovy.util.XmlSlurper
```
Comment (JakeWharton) [inline butterknife-gradle-plugin/src/main/java/butterknife/plugin/ButterKnifePlugin.kt]: I hate absolutely everything about this type's FQCN: Groovy, "util", XML, and "Slurper"...

File: gradle/wrapper/gradle-wrapper.properties (hunk 1 above)
Comment (runningcode) [reply gradle/wrapper/gradle-wrapper.properties]: the jar did change. made a PR to update it: https://github.com/JakeWharton/butterknife/pull/1191

Comment (JakeWharton) [reply gradle/wrapper/gradle-wrapper.properties]: It didn't in other projects I've upgraded

Comment (vanniktech) [reply gradle/wrapper/gradle-wrapper.properties]: Could be that someone forgot to change it when going from 4.x to 4.4.1
