### PR TITLE
Scope symbol IDs per element package name

### LINKED ISSUE #779: ButterKnife generates ViewBinding class with wrong resource ID
I am using a 3rd-party library in our project, and compilation works fine, but the app crashes when it starts up. I looked at the logcat and generate source code, it seems the generated source code has the wrong resource ID.

For example, the source file is

```
class HomeActivity ... {
    @BindView(R2.id.mode_transition_layout) AppModeTransitionLayout modeTransitionLayout;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);
```

The generated `HomeActivity_ViewBinding` class has

```
  @UiThread
  public HomeActivity_ViewBinding(T target, View source) {
    this.target = target;

    target.modeTransitionLayout = Utils.findRequiredViewAsType(source, R.id.infant_description_text, "field 'modeTransitionLayout'", AppModeTransitionLayout.class);
  }
```

`R.id.infant_description_text` is a different resource ID, and I'd assume here should use `R.id.mode_transition_layout`. 

At the runtime I get an exception says
`java.lang.IllegalStateException: Required view 'infant_description_text' with ID 2131822441 for field 'modeTransitionLayout' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.`

We are using ButterKnife 8.4.0.

Any help is highly appreciated!

### PR DESCRIPTION
**Pull request by felipecsl**
the integer ID itself is not enough to correctly identify a symbol. We need to scope that somehow in order to prevent clashes. This can be observed in a multiple modules project where butterknife is used in modules that depend on other modules that also use Butterknife.
Since IDs can repeat across modules, we need to scope them according to the package name of the current element being evaluated.
This PR fixes #779

### CODE REVIEW

File: butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java [hunk 1]
```diff
@@ -1231,17 +1246,20 @@ private void scanForRClasses(RoundEnvironment env) {
       for (Element element : env.getElementsAnnotatedWith(annotation)) {
         JCTree tree = (JCTree) trees.getTree(element, getMirror(element, annotation));
         if (tree != null) { // tree can be null if the references are compiled types and not source
+          String respectivePackageName =
+              elementUtils.getPackageOf(element).getQualifiedName().toString();
+          scanner.setCurrentPackageName(respectivePackageName);
```
Comment (felipecsl) [inline butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java]: This is pretty janky, but couldn't figure out a simpler way to do this. Suggestions welcome

File: butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java [hunk 2]
```diff
@@ -1284,28 +1302,38 @@ private void parseCompiledR(TypeElement rClass) {
   }
 
   private static class RClassScanner extends TreeScanner {
-    private final Set<String> rClasses = new LinkedHashSet<>();
+    // Maps the currently evaulated packageName to R Classes
+    private final Map<String, String> rClasses = new LinkedHashMap<>();
```
Comment (felipecsl) [inline butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java]: This is also a bit confusing

**Comment by felipecsl** [comment]
@kageiit wonder if you could take a look too, since you made this change originally

File: butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java [hunk 3]
```diff
@@ -1215,11 +1230,11 @@ private static AnnotationMirror getMirror(Element element,
     return null;
   }
 
-  private Id getId(int id) {
-    if (symbols.get(id) == null) {
-      symbols.put(id, new Id(id));
+  private Id getId(QualifiedId qualifiedId) {
```
Comment (kageiit) [inline butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java]: QualifiedId already has the id as part of it right? why do you still need the symbol map

File: butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java [hunk 4]
```diff
@@ -1231,17 +1246,20 @@ private void scanForRClasses(RoundEnvironment env) {
...
 
-    for (String rClass : scanner.getRClasses()) {
-      parseRClass(rClass);
+    for (Map.Entry<String, String> rClass : scanner.getRClasses().entrySet()) {
+      parseRClass(rClass.getKey(), rClass.getValue());
     }
   }
 
-  private void parseRClass(String rClass) {
+  private void parseRClass(String respectivePackageName, String rClass) {
```
Comment (kageiit) [inline butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java]: rename to rPackageName?

File: butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java (hunk 3 above)
Comment (felipecsl) [inline butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java]: Correct. I kept the Map just for the fast lookup

File: butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java (hunk 4 above)
Comment (felipecsl) [inline butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java]: sure!

**Comment by felipecsl** [comment]
@JakeWharton friendly ping!

**Comment by JakeWharton** [comment]
Monday at earliest. Traveling.

**Comment by felipecsl** [comment]
No worries, I just realized that this is not quite right yet. More updates coming

**Comment by kunong** [comment]
@felipecsl anymore updates coming? I'm a guy that waiting this fix. :)

**Comment by felipecsl** [comment]
@kunong yep, planning to finish today or tomorrow

**Comment by javajoker** [comment]
@felipecsl , any update on this issue? Thanks, Ning

**Comment by felipecsl** [comment]
no updates yet. We stopped seeing this issue so it's not burning anymore.

**Comment by mrhether** [comment]
@felipecsl what exactly still needs to be completed here? Once we know, then hopefully someone can work on it.

**Comment by mrhether** [comment]
@felipecsl what still needs to be done here?

**Comment by felipecsl** [comment]
@mrhether If I'm not mistaken, this change breaks usage of ButterKnife when you're not using it as a gradle plugin. If you always use it as a plugin, then it should work fine.

**Comment by mrhether** [comment]
@felipecsl Is this hosted anywhere?

**Comment by felipecsl** [comment]
Nope

**Comment by felipecsl** [comment]
Alright thanks to @BenSchwab 's https://github.com/airbnb/butterknife/commit/b0aa4ad417ab0867a8bbd19c5d9461c835996e6f we this is finally functional and ready for review.
We've been using it internally for a ~week and it seems to have fixed the bug.
@JakeWharton PTAL at your earliest convenience 😄

File: build.gradle [hunk 5]
```diff
@@ -37,7 +37,7 @@ subprojects { project ->
       }
     }
     dependencies {
-      classpath 'com.android.tools.build:gradle:2.2.2'
+      classpath 'com.android.tools.build:gradle:2.3.0-rc1'
```
Comment (JakeWharton) [inline build.gradle]: Is this required? Non-final releases are timeboxed and I don't want to commit code that uses pre-release versions because that makes the commit unbuildable after a month or two.

**Comment by JakeWharton** [comment]
Looks like there's a checkstyle failure.

File: build.gradle (hunk 5 above)
Comment (felipecsl) [inline build.gradle]: not required. it was just Android Studio being annoying. Reverting now..

**Comment by felipecsl** [comment]
Green and ready to go 🎉
