### PR TITLE
Avoid all @OnClick events may not working

### LINKED ISSUE #1619: All methods annotated with @OnClick may not work
Today i found all click methods annotated with `@OnClick` are not working in my code.

After debugging, i found something wrong with `DebouncingOnClickListener`, 
the static field `enabled` always stays in `false`.

```
public abstract class DebouncingOnClickListener implements View.OnClickListener {
  static boolean enabled = true;

  private static final Runnable ENABLE_AGAIN = () -> enabled = true;

  @Override public final void onClick(View v) {
    if (enabled) {
      enabled = false;
      //we can NOT guarantee that ENABLE_AGAIN will be executed.
      v.post(ENABLE_AGAIN);
      doClick(v);
    }
  }

  public abstract void doClick(View v);
}
```

Certain cases can lead to this, here is my case:
 i called `someButton.performClick()` programmatically while `someButton` is not attached to window and will not be attached to window. `DebouncingOnClickListener` of `someButton`  set `enabled` to `false`. 
At this time `ENABLE_AGAIN` will never get chance to be executed.

So, do we have some other `DebouncingOnClickListener` implementations to avoid this?

Thanks in advance.

### PR DESCRIPTION
**Pull request by lonnyzhang423**
Avoid `DebouncingOnClickListener` static field `enabled` staying in `false` state. 

Fixes #1619

### CODE REVIEW

**Comment by lonnyzhang423** [comment]
Fixes issue #1619

File: butterknife-runtime/src/main/java/butterknife/internal/DebouncingOnClickListener.java [hunk 1]
```diff
@@ -13,8 +15,14 @@
 
   @Override public final void onClick(View v) {
     if (enabled) {
-      enabled = false;
-      v.post(ENABLE_AGAIN);
```
Comment (JakeWharton) [inline butterknife-runtime/src/main/java/butterknife/internal/DebouncingOnClickListener.java:17]: We can switch this to post to the main looper directly rather than going through the view. That way we don't need to check for attach.

Comment (lonnyzhang423) [reply butterknife-runtime/src/main/java/butterknife/internal/DebouncingOnClickListener.java:17]: Thanks for your reply.

Yes, i updated my code and pushed to my fork. But the Travis CI build failed, i don't known why...

CI failed log:

```
Task :butterknife-integration-test:connectedCodegenDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':butterknife-integration-test:connectedCodegenDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/travis/build/JakeWharton/butterknife/butterknife-integration-test/build/reports/androidTests/connected/flavors/CODEGEN/index.html
```

Comment (lonnyzhang423) [reply butterknife-runtime/src/main/java/butterknife/internal/DebouncingOnClickListener.java:17]: Hi Jake, I fixed unit test errors and The Travis CI build passed😀.

**Comment by JakeWharton** [comment]
I changed the test so that it's black box instead of mucking with the internals through reflection. Thanks! Will do a release now.

**Comment by lonnyzhang423** [comment]
Well done, thanks.
